spring:
  datasource:
    url: jdbc:mysql://localhost:33061/mybatis3?useUnicode=true&useSSL=true&useCharacterEncoding=utf-8&serverTimezone=JST
    username: user01
    password: 123456
mybatis:
  #  type-aliases-package: com.github.eulerlcs.study.mybatis3
  config-location: classpath:mybatis-config.xml
logging:
  level:
    root: info
